---
title: "DecisionTree"
author: "Mike"
date: "2020/4/6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reference

1. [**(推薦)**决策树（decision tree）(一)——构造决策树方法](https://blog.csdn.net/u012328159/article/details/70184415)

2. [**(推薦)**决策树（decision tree）(二)——剪枝](https://blog.csdn.net/u012328159/article/details/79285214)

3. [**(推薦)**决策树（decision tree）(三)——连续值处理](https://blog.csdn.net/u012328159/article/details/79396893)

4. [**(推薦)**决策树（decision tree）（四）——缺失值处理](https://blog.csdn.net/u012328159/article/details/79413610)

5.  [Decision Tree 決策樹 | CART, Conditional Inference Tree, RandomForest](https://www.jamleecute.com/decision-tree-cart-%E6%B1%BA%E7%AD%96%E6%A8%B9/)

6. [機器學習：決策樹總結｜ID3 C4.5/C5.0 CHAID CART與QUEST](https://kknews.cc/zh-tw/tech/m36obez.html)

7. [決策樹(Decision Tree)以及隨機森林(Random Forest)介紹](https://medium.com/jameslearningnote/%E8%B3%87%E6%96%99%E5%88%86%E6%9E%90-%E6%A9%9F%E5%99%A8%E5%AD%B8%E7%BF%92-%E7%AC%AC3-5%E8%AC%9B-%E6%B1%BA%E7%AD%96%E6%A8%B9-decision-tree-%E4%BB%A5%E5%8F%8A%E9%9A%A8%E6%A9%9F%E6%A3%AE%E6%9E%97-random-forest-%E4%BB%8B%E7%B4%B9-7079b0ddfbda)

8. [HOW DECISION TREE ALGORITHM WORKS](http://dataaspirant.com/2017/01/30/how-decision-tree-algorithm-works/)

9. [C4.5 Pessimistic Error Pruning，PEP](http://gitlinux.net/2019-06-04-C45/)


## Algorithm


| Algorithm |       Data Type        |       Feature Selection       | Pruning Rule | Missing Value |
| --------- | ---------------------- | ----------------------------- | ------------ | ------------- |
|    ID3    |      Discrete          | Information Gain (Entropy)    |  No Pruning  |  Not Allowed  |
|   C4.5    | Discrete & Continueous | Information Gain Ratio(Ent,IV)|     PEP      |    Allowed    |
|   CHAID   | Discrete & Continueous |    Chisquare Test p value     | Pruning Rule |       ?       |
|   CART    | Discrete & Continueous |         Gini Index            |  No Pruning  |       ?       |
|   QUEST   | Discrete & Continueous | Chisquare or F Test p value   |  No Pruning  |       ?       |
|   C5.0    | Discrete & Continueous |      I stll dont know         | Pruning Rule |       ?       |



















